### ISSUE TITLE
limits in nested queries

### ISSUE THREAD

**Issue by GonerGenesis** [jycouet/remult-kit#27]
on using `kitStoreItem` with included Relations i somewhere get an default limit of 25 items for related objects for example on:
```
@Entity<Frame>('frames', {
	allowApiCrud: true,
	dbName: 'frame'
})
export class Frame {
	@Fields.cuid()
	id!: string

	@Fields.boolean()
	is_symmetric: boolean = true

	@Fields.number()
	frame_pos!: number

	@Fields.createdAt()
	created_at = new Date()

	@Fields.date()
	modified_at = new Date()

	@Fields.string()
	ship_id!: string

	@Relations.toMany(() => Framepoint)
	framepoints?: Framepoint[]

	@Relations.toMany(() => Framesegment)
	framesegments?: Framesegment[]

	@Relations.toOne(() => Ship, { field: 'ship_id', defaultIncluded: true })
	ship!: Ship
	// @Field(() => Ship, { allowNull: true })
	// ship?: Ship

	// Relations toMany

	@Relations.toOne<Frame, Framecsvalue>(() => Framecsvalue, {
		fields: {
			frame_id: "id",
		},
		allowNull: true,
	})
	framecsvalue?: Framecsvalue;

	// @Relations.toMany(() => Framecsvalue)
	// framecsvalues?: Framecsvalue[]
}
```
with
```
const frameRepo = remult.repo(Frame);
const frame = kitStoreItem(frameRepo);

$: frameID = $page.url.searchParams.get('frame');

$: browser &&
frameID &&
frame.fetch(frameID, {
	include: {
		framepoints: { include: { stiffener: true }, limit: 1000},
		framesegments: { include: { start_point: true, end_point: true }, limit: 1000 },
		framecsvalue: true
	}
})
```
I've to raise the limit in the includes, if not it defaults to 25

**Comment by jycouet** [comment]
Yes, the default is `25`.
You can change this default value in `remultKit` settings with `defaultGetLimit`.

On my side, I like to have a "fast/small" limit by default, and increase it manually when needed and beeing explicite.

If you agree, I let you close, or comment.

**Comment by GonerGenesis** [comment]
Ok, reasonable. I just thought it should default to 100, because it was stated in a comment somewhere (but I can't find this comment anymore).

**Comment by jycouet** [comment]
> I just thought it should default to 100

You mean, the "default default". It's a number, sooo quite subjective. 
Anyhow you can tune it, so all good ;)

**Comment by GonerGenesis** [comment]
100 is the remult default default or? xD
Nevermind

**Comment by jycouet** [comment]
Haha, I don't remember, but it's possible 😅
